services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
#      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/ssl/:/etc/nginx/ssl/
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - ../data/mariadb/mysql:/var/lib/mysql
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
     - .env
    volumes:
      - ./requirements/wordpress/php-fpm.conf:/etc/php/php-fpm.conf
    restart: always