services:
  reverseproxy:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
#      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/scripts:/scripts
    entrypoint: /bin/sh /scripts/gencert.sh
    restart: always
  
  database:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
  
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
     - .env
    volumes:
      - ./requirements/wordpress/php-fpm.conf:/etc/php/php-fpm.conf
    restart: always