services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
#      - 80:80
      - 443:443
    volumes:
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/ssl/:/etc/nginx/ssl/
      - wordpress:/var/www/wordpress
      - ruinformatique:/var/www/ruinformatique
    networks:
      - inception-network
    restart: on-failure
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - ./secrets/dump.sql:/dump.sql:ro
      - mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
     - .env
    volumes:
      - wordpress:/var/www/wordpress
      - ./requirements/wordpress/php-fpm.conf:/etc/php83/php-fpm.conf
      - ./requirements/wordpress/wp-config.php:/var/www/wordpress/wp-config.php
    networks:
      - inception-network
    restart: on-failure

  redis:
    container_name: redis
    build: ./requirements/redis
    env_file:
     - .env
    networks:
      - inception-network
    restart: on-failure
  
  vsftpd:
    container_name: vsftpd
    build: ./requirements/vsftpd
    env_file:
     - .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 21:21
    restart: on-failure
  
  ruinformatique-www:
    container_name: ruinformatique-www
    build: ./requirements/ruinformatique-www
    volumes:
      - ruinformatique:/var/www/ruinformatique
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  ruinformatique:
    driver: local
    driver_opts:
      type: none
      device: ~/data/ruinformatique
      o: bind

networks:
  inception-network:
    driver: bridge