services:
  reverseproxy:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
  
  database:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - srcs/.env
    ports:
      - 3306:3306
    restart: always